streams:
  # - https://cam.visitthirsk.uk/images/webcam70/mjpg/video.mjpg
  # - rtsp://admin:Admin12345@Bhascommune.ddns.net:554/cam/realmonitor?channel=1&subtype=0
  # - http://90.94.183.168:8080/mjpg/video.mjpg
  # - rtsp://admin:Admin12345@192.168.1.107:554/cam/realmonitor?channel=1&subtype=0
  - "rtsp://admin:admin123@10.0.0.200:554/h264/ch1/main/av_stream"
  - "rtsp://admin:admin123@10.0.0.200:554/h264/ch2/main/av_stream"
  - "rtsp://admin:admin123@10.0.0.200:554/h264/ch3/main/av_stream"
emails:
  - walid-berkane@outlook.com
  - fatima.eljaimi17@gmail.com
  - wiamrabhi2000@gmail.com